/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "archivador.h"


void
archivador_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	Args_Escribir  escribir_1_arg;
	Datos  *result_2;
	Args_Leer  leer_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ARCHIVADOR, VERSION_ACTUAL, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	/* me preparo para escribir */
	escribir_1_arg.nombreArchivo = "hola.txt";
	escribir_1_arg.posicion = 0;
	escribir_1_arg.dato.long_datos = 15;
	escribir_1_arg.dato.buffer[15]="hola de nuevo";
	result_1 = escribir_1(&escribir_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("cant de bytes escrita ");					
	}

	/*me preparo para leer*//*
	leer_1_arg.nombreArchivo = "prueba.txt";
	leer_1_arg.posicion = 4;
	leer_1_arg.long_datos = 10;	
	result_2 = leer_1(&leer_1_arg, clnt);
	
	if (result_2 == (Datos *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("tamaño del archivo ");
		printf ("%d \n",result_2->long_datos);				
	}*/

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	archivador_1 (host);
	exit (0);
}
